### ISSUE TITLE
mismatches in 5 pair names

### ISSUE THREAD

**Issue by ulfschaefer** [quick-lab/SARS-CoV-2#15]
Morning

There are 5 primer pairs for which the indexes at the end of the names don't match. These are:

SARS-CoV-2_400_3_LEFT_1		
SARS-CoV-2_400_3_RIGHT_0

SARS-CoV-2_400_31_LEFT_1
SARS-CoV-2_400_31_RIGHT_0

SARS-CoV-2_400_62_LEFT_2
SARS-CoV-2_400_62_RIGHT_0

SARS-CoV-2_400_89_LEFT_2
SARS-CoV-2_400_89_RIGHT_0

SARS-CoV-2_400_96_LEFT_1
SARS-CoV-2_400_96_RIGHT_0

This causes reads in these regions to be consistently dropped when these primers are used together with the Artic ONT pipeline, because of this line of code:

https://github.com/artic-network/fieldbioinformatics/blob/8eb6a0c619030b137f8c97545aa1b763b94446db/artic/align_trim.py#L200

The problem disappears when we use a local version of the repo in which we have renamed the RIGHT halves of these pairs to make the names consistent.

**Comment by ChrisgKent** [comment]
Hi, 

These primer names use the new standardised naming system of;  
- ```{scheme-name}_{amplicon-number}_{direction}_{primer-number}```

We are aware of this causing breaking changes in some of the artic pipelines and are working on fixing it. However, in the meantime, we have the "pipeline friendly" of the scheme in the [artic-repo](https://github.com/artic-network/primer-schemes/tree/e6ddb7c4a21a65e1e4ae3c21129f9d08c2cac12f/nCoV-2019/V5.3.2), which should be the version pulled into the pipelines. 

We will have a blog post explaining the need for, and requirements of the naming system soon! So people can update custom pipelines

**Comment by ulfschaefer** [comment]
Ok. Thank you for your reply. The pipeline friendly version of the scheme was not available at the time for us, but good that it is now.
